blog/urls.py
from django.urls import path
from .import views


app_name ='blog'
urlpatterns = [
    path('',views.post_list,name='post_list'),
    path('<int:id>/',views.post_detail,name='post_detail'),
    path('new/',views.new_post,name='new_post'),
    path('<int:id>/edit',views.edit_post,name='edit_post'),
    path('<int:id>/delete',views.delete_post,name='delete_post'),
    # path('cbv',views.PostList.as_view(),name='cbv_post_list'),
    # path('cbv/<int:pk>',views.PostDetail.as_view(),name='cbv_post_detail'),
    # path('cbv/<int:pk>/delete',views.PostDelete.as_view(),name='cbv_post_delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls',namespace='blog'))
]
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=1000,null=True,blank=True)
    publish_date = models.DateField(default=timezone.now)
    update_date = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='posts/')
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'My Post'
        ordering = ['publish_date']
class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        

blog/forms.py
from django import forms
from .models import Post



class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        exclude = ('publish_date',)

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from.models import Post
from . forms import PostForm
# Create your views here.

def post_list(request):
    all_posts = Post.objects.all()
    context = {'all_posts':all_posts}
    return render(request,'blog/post_list.html',context)

def post_detail(request,id):
    post = get_object_or_404 (Post,id=id)
    return render(request,'blog/post_detail.html',{'post':post})

def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = PostForm()
    return render (request,'blog/new_post.html',{'form':form})


def edit_post(request,id):
    post = get_object_or_404 (Post,id=id)
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES,instance=post)
        if form.is_valid():
            form.save()
    else:
        form = PostForm(instance=post)
    return render (request,'blog/new_post.html',{'form':form})

def delete_post(request,id):
    post = get_object_or_404 (Post,id=id)
    post.delete()
    return redirect('/blog')


# from django.views.generic import ListView,DetailView,DeleteView

# class PostList(ListView):
#     model = Post

# class PostDetail(DetailView):
#     model = Post

# class PostDelete(DeleteView):
#     model = Post
#     success_url = '/blog/cbv'

blog/templates/blog/detail.html
<a href="{% url 'blog:post_list' %}"><h1>Our Blog</h1></a>

<h1>{{object}}</h1>
<h3>{{post.publish_date}}</h3>
<h5>{{post.content}}</h5>

<a href="{% url 'blog:edit_post' post.id %}">Edit Post</a>
<br />
<a href="{% url 'blog:delete_post' post.id %}">Delete Post</a>

blog/templates/blog/list.html
<a href="{% url 'blog:post_list' %}"><h1>Our Blog</h1></a>
<a href="{% url 'blog:new_post' %}">New Post</a>
<hr />
{% for post in all_posts %}
<a href="{% url 'blog:post_detail' post.id %}"><h3>{{post}}</h3></a>
{% endfor %}

blog/templates/blog/new_post.html
<a href="{% url 'blog:post_list' %}"><h1>Our Blog</h1></a>

<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" />
</form>

blog/templates/blog/post_confirm_delete.html
{% block content %}
    <div class="container">

        <!-- Form -->
        <form action="" method="post">

            {% csrf_token %}

            <div class="col-sm-9">
                <div class="jumbotron">
                    <h3>Are you sure you want to delete Post: "{{ post.title }}"?</h3>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-9">

                    <!-- Submit button -->
                    <button type="submit" class="btn btn-primary btn-block">Confirm</button>

                </div>
            </div>

        </form>

    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block content %}
			    <div class="blog-post-body">
				    <figure class="blog-banner">
				        <a href="https://made4dev.com"><img class="img-fluid" src="{{post.image.url}}" alt="image"></a>
				        <figcaption class="mt-2 text-center image-caption">Image Credit: <a class="theme-link" href="https://made4dev.com?ref=devblog" target="_blank">made4dev.com (Premium Programming T-shirts)</a></figcaption>
				    </figure>
				    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. </p>
				    
				    <h3 class="mt-5 mb-3">{{post.title}}</h3>
				    <p>{{post.content}}</p>
				</div>
		
				{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
	    {% block content %}
				{% for obj in all_posts %}
				<div class="item mb-5">
				    <div class="row g-3 g-xl-0">
					    <div class="col-2 col-xl-3">
					        <img class="img-fluid post-thumb " src="{{obj.image.url}} " alt="image">
					    </div>
					    <div class="col">
						    <h3 class="title mb-1"><a class="text-link" href="{% url 'blog:post_detail' obj.id %}">{{obj.title}}</a></h3>
						    <div class="meta mb-1"><span class="date">Published 2 days ago</span><span class="time">5 min read</span><span class="comment"><a class="text-link" href="#">8 comments</a></span></div>
						    <div class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies...</div>
						    <a class="text-link" href="blog-post.html">Read more &rarr;</a>
					    </div><!--//col-->
				    </div><!--//row-->
			    </div><!--//item-->
			    
				{% endfor %}
			    {% endblock content %}
			   

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>DevBlog - Bootstrap 5 Blog Template For Developers</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
	<script defer src="{% static 'assets/fontawesome/js/all.min.js' %} "></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-1.css' %} ">

</head> 

<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a class="no-text-decoration" href="index.html">Anthony's Blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'assets/images/profile.png' %} " alt="image" >			
					
					<div class="bio mb-3">Hi, my name is Anthony Doe. Briefly introduce yourself here. You can also provide a link to the about page.<br><a href="about.html">Find out more about me</a></div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr> 
				</div><!--//profile-section-->
				
				<ul class="navbar-nav flex-column text-start">
					<li class="nav-item">
					    <a class="nav-link active" href="index.html"><i class="fas fa-home fa-fw me-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="blog-post.html"><i class="fas fa-bookmark fa-fw me-2"></i>Blog Post</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="about.html"><i class="fas fa-user fa-fw me-2"></i>About Me</a>
					</li>
				</ul>
				
				<div class="my-2 my-md-3">
				    <a class="btn btn-primary" href="https://themes.3rdwavemedia.com/" target="_blank">Get in Touch</a>
				</div>
			</div>
		</nav>
    </header>
    
    <div class="main-wrapper">
	    
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center single-col-max-width">
			    <h2 class="heading">DevBlog - A Blog Template Made For Developers</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <div class="single-form-max-width pt-3 mx-auto">
				    <form class="signup-form row g-2 g-lg-2 align-items-center">
	                    <div class="col-12 col-md-9">
	                        <label class="sr-only" for="semail">Your email</label>
	                        <input type="email" id="semail" name="semail1" class="form-control me-md-1 semail" placeholder="Enter email">
	                    </div>
	                    <div class="col-12 col-md-2">
	                        <button type="submit" class="btn btn-primary">Subscribe</button>
	                    </div>
	                </form><!--//signup-form-->
			    </div><!--//single-form-max-width-->
		    </div><!--//container-->
	    </section>
	    
	    
	    <section class="blog-list px-3 py-5 p-md-5">
		    <div class="container single-col-max-width">
				{% block content %}{% endblock content %}
			    
			    <nav class="blog-nav nav nav-justified my-5">
				  <a class="nav-link-prev nav-item nav-link d-none rounded-left" href="#">Previous<i class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
				  <a class="nav-link-next nav-item nav-link rounded" href="#">Next<i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
				</nav>
				
		    </div>
	    </section>
	    
	    <footer class="footer text-center py-2 theme-bg-dark">
		   
	        <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">Designed with <span class="sr-only">love</span><i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="https://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
		   
	    </footer>
    
    </div><!--//main-wrapper-->

       
    <!-- Javascript -->          
    <script src="{% static 'assets/plugins/popper.min.js' %} "></script> 
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %} "></script> 

    

</body>
</html> 